<testsuites>
  <testsuite name="step graph" tests="10" skipped="0" failures="2" time="1469.617799393">
    <properties></properties>
    <testcase name="All images are built and tagged into stable" time="1.54e-06"></testcase>
    <testcase name="Find the input image managed-services-integration-tests and tag it into the pipeline" time="0.033184271"></testcase>
    <testcase name="Find the input image openshift-cli-installer and tag it into the pipeline" time="0.023988171"></testcase>
    <testcase name="Import the release payload &#34;latest&#34; from an external source" time="122.396547249"></testcase>
    <testcase name="Run multi-stage test post phase" time="577.869285696">
      <system-out>The collected steps of multi-stage phase post.</system-out>
    </testcase>
    <testcase name="Run multi-stage test pre phase" time="740.137169522">
      <system-out>The collected steps of multi-stage phase pre.</system-out>
    </testcase>
    <testcase name="Run multi-stage test test phase" time="28.982595041">
      <failure message="">&#34;test-pass-setup-fail-test&#34; pod &#34;test-pass-setup-fail-test-cluster-msi-tests&#34; failed: could not watch pod: the pod ci-op-l1tbw7p8/test-pass-setup-fail-test-cluster-msi-tests failed after 29s (failed containers: test): ContainerFailed one or more containers exited&#xA;&#xA;Container test exited with code 1, reason Error&#xA;---&#xA;ied: &#39;/managed-services-integration-tests/.pytest_cache&#39;&#xA;    config.cache.set(&#34;cache/nodeids&#34;, sorted(self.cached_nodeids))&#xA;&#xA;.venv/lib/python3.12/site-packages/_pytest/cacheprovider.py:397&#xA;  /managed-services-integration-tests/.venv/lib/python3.12/site-packages/_pytest/cacheprovider.py:397: PytestCacheWarning: could not create cache path /managed-services-integration-tests/.pytest_cache/v/cache/lastfailed: [Errno 13] Permission denied: &#39;/managed-services-integration-tests/.pytest_cache&#39;&#xA;    config.cache.set(&#34;cache/lastfailed&#34;, self.lastfailed)&#xA;&#xA;.venv/lib/python3.12/site-packages/_pytest/stepwise.py:56&#xA;  /managed-services-integration-tests/.venv/lib/python3.12/site-packages/_pytest/stepwise.py:56: PytestCacheWarning: could not create cache path /managed-services-integration-tests/.pytest_cache/v/cache/stepwise: [Errno 13] Permission denied: &#39;/managed-services-integration-tests/.pytest_cache&#39;&#xA;    session.config.cache.set(STEPWISE_CACHE_DIR, [])&#xA;&#xA;-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html&#xA;------------ generated xml file: /logs/artifacts/xunit_results.xml -------------&#xA;=========================== short test summary info ============================&#xA;FAILED tests/cluster_sanity/test_cluster_sanity.py::test_multi_clusters_sanity[] - ocp_utilities.exceptions.PodsFailedOrPendingError: The following pods are failed or pending:&#xA;&#x9;name: deployment-validation-operator-catalog-4k8s2, namespace: openshift-deployment-validation-operator, status: Pending&#xA;&#x9;name: route-monitor-operator-controller-manager-5cc995c8d4-c8l98, namespace: openshift-route-monitor-operator, status: Pending&#xA;================= 1 failed, 13 deselected, 7 warnings in 8.75s =================&#xA;{&#34;component&#34;:&#34;entrypoint&#34;,&#34;error&#34;:&#34;wrapped process failed: exit status 1&#34;,&#34;file&#34;:&#34;k8s.io/test-infra/prow/entrypoint/run.go:84&#34;,&#34;func&#34;:&#34;k8s.io/test-infra/prow/entrypoint.Options.internalRun&#34;,&#34;level&#34;:&#34;error&#34;,&#34;msg&#34;:&#34;Error executing test process&#34;,&#34;severity&#34;:&#34;error&#34;,&#34;time&#34;:&#34;2024-02-11T15:23:29Z&#34;}&#xA;error: failed to execute wrapped command: exit status 1&#xA;---&#xA;Link to step on registry info site: https://steps.ci.openshift.org/reference/cluster-msi-tests&#xA;Link to job on registry info site: https://steps.ci.openshift.org/job?org=CSPI-QE&amp;repo=MSI&amp;branch=multi-cluster-smoke&amp;test=test-pass-setup-fail-test&amp;variant=v4.14</failure>
      <system-out>The collected steps of multi-stage phase test.</system-out>
    </testcase>
    <testcase name="Run multi-stage test test-pass-setup-fail-test - test-pass-setup-fail-test-cluster-install container test" time="712"></testcase>
    <testcase name="Run multi-stage test test-pass-setup-fail-test - test-pass-setup-fail-test-cluster-msi-tests container test" time="21">
      <failure message="">ied: &#39;/managed-services-integration-tests/.pytest_cache&#39;&#xA;    config.cache.set(&#34;cache/nodeids&#34;, sorted(self.cached_nodeids))&#xA;&#xA;.venv/lib/python3.12/site-packages/_pytest/cacheprovider.py:397&#xA;  /managed-services-integration-tests/.venv/lib/python3.12/site-packages/_pytest/cacheprovider.py:397: PytestCacheWarning: could not create cache path /managed-services-integration-tests/.pytest_cache/v/cache/lastfailed: [Errno 13] Permission denied: &#39;/managed-services-integration-tests/.pytest_cache&#39;&#xA;    config.cache.set(&#34;cache/lastfailed&#34;, self.lastfailed)&#xA;&#xA;.venv/lib/python3.12/site-packages/_pytest/stepwise.py:56&#xA;  /managed-services-integration-tests/.venv/lib/python3.12/site-packages/_pytest/stepwise.py:56: PytestCacheWarning: could not create cache path /managed-services-integration-tests/.pytest_cache/v/cache/stepwise: [Errno 13] Permission denied: &#39;/managed-services-integration-tests/.pytest_cache&#39;&#xA;    session.config.cache.set(STEPWISE_CACHE_DIR, [])&#xA;&#xA;-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html&#xA;------------ generated xml file: /logs/artifacts/xunit_results.xml -------------&#xA;=========================== short test summary info ============================&#xA;FAILED tests/cluster_sanity/test_cluster_sanity.py::test_multi_clusters_sanity[] - ocp_utilities.exceptions.PodsFailedOrPendingError: The following pods are failed or pending:&#xA;&#x9;name: deployment-validation-operator-catalog-4k8s2, namespace: openshift-deployment-validation-operator, status: Pending&#xA;&#x9;name: route-monitor-operator-controller-manager-5cc995c8d4-c8l98, namespace: openshift-route-monitor-operator, status: Pending&#xA;================= 1 failed, 13 deselected, 7 warnings in 8.75s =================&#xA;{&#34;component&#34;:&#34;entrypoint&#34;,&#34;error&#34;:&#34;wrapped process failed: exit status 1&#34;,&#34;file&#34;:&#34;k8s.io/test-infra/prow/entrypoint/run.go:84&#34;,&#34;func&#34;:&#34;k8s.io/test-infra/prow/entrypoint.Options.internalRun&#34;,&#34;level&#34;:&#34;error&#34;,&#34;msg&#34;:&#34;Error executing test process&#34;,&#34;severity&#34;:&#34;error&#34;,&#34;time&#34;:&#34;2024-02-11T15:23:29Z&#34;}&#xA;error: failed to execute wrapped command: exit status 1&#xA;</failure>
    </testcase>
    <testcase name="Run multi-stage test test-pass-setup-fail-test - test-pass-setup-fail-test-cluster-uninstall container test" time="553"></testcase>
  </testsuite>
</testsuites>
